### ISSUE TITLE
Episodes not being downloaded - ARM arch

### ISSUE THREAD

**Issue by sasagr** [dgalli1/DockerPremiumize#1]
Hi. I found this project very interesting and so I decided to install the docker on my raspberry pi.
The installation was successful, at least without any error. Docker are running. I did not make any setting adjustments in Sonarr. I only changed the 3 settings in the yaml file (API KEY and folders ids).
I added a couple of series and started the autosearch and realised that I needed to chmod 777 the blackhole folder for sonarr to be able to access it. After that no other error but the queue only get populated in the history and nothing seems to be happening in Premiumize. I see nothing in the transfer activity in the cloud.
Am I missing some other setting?
Pls advise

**Comment by dgalli1** [comment]
Most likely your folder ids are wrong.
Can you try to manually put a torrent inside the folder blackhole in the project root?
Also the docker logs for the container premiumizephp would be interesting. 
`docker-compose logs premiumizephp
`

**Comment by sasagr** [comment]
in the folder /home/pi/DockerPremiumize/blackhole I have a few .magnet files like for example:
Riviera S03E01 1080p WEB-DL x264-ROCCaT.magnet

In the log I see long list of this error:
pi@raspberrypi:~/DockerPremiumize $ docker-compose logs premiumizephp
Attaching to premiumizephp
premiumizephp    | standard_init_linux.go:211: exec user process caused "exec format error"

In Portainer I see all the containers are running.

The keys/ids are as follows (just changed last characters):
environment: 
      - API_KEY=zrejk9y4uuxxxxxx
      - LIBRARY_FOLDER=tKvAwMA2IhUqaEM0vwxxxx
      - DOWNLOAD_FOLDER=PiOgQ4D10DQ0jGd1fmxxxx

Any idea where it could be the issue?

**Comment by sasagr** [comment]
I read the this error may occur when the architecture is not compatible. Note that the raspberry pi has an ARM architecture.
Is this the case?

**Comment by dgalli1** [comment]
Yes that has to be it, i only validated it with X86.
I don't know how to build a container for arm on X86. But you should be able to do it yourself.
```bash
cd premiumizephp
docker build -t premiumizephp_local .
cd ..
sed -i 's/dgalli1\/premiumizephp:1.0/premiumizephp_local:latest/g' docker-compose.yml
```

**Comment by sasagr** [comment]
I run your above commands, no error. I restarted the containers but still I m getting the same error in the log. Shall I do anything else after those commands? maybe 'docker-compose up -d' ?

**Comment by dgalli1** [comment]
Yes ofcourse you have to run docker-compose down and then docker-compose up -d

**Comment by sasagr** [comment]
it worked, very well. All seems fine... episodes were all downloaded in the cloud and moved to sonarr folder.

One more question.. I would like to be able to connect to sonarr and jacket from another computer but http://<ip>:8989 does not work. Can you suggest me a quick solution? Thanks in advance

**Comment by dgalli1** [comment]
I have a preconfigured reverse proxy in the compose file. You can use that one and just edit the port 
```yaml
  reverseproxy:
      image: nginx:latest
      ports:
          - "YOUR_NEW_PORT:80"
      volumes:
          - ./premiumizephp:/code
          - ./nginx.conf:/etc/nginx/nginx.conf
```

Edit: Jackett will be available at http://host/jackett

**Comment by sasagr** [comment]
Just to be sure I understood right. 
My raspberrypi local ip is 192.168.1.77. To access sonarr from another machine in the same network I can go to http://192.168.1.77/sonarr (for jacket http://192.168.1.77/jacket) but first I have to edit the compose file REVERSEPROXY removing the 127.0.0.1 and if I want changing port to 81:80 for example if port 80 is already busy. 
Is that right?

**Comment by dgalli1** [comment]
Almost sonarr will be accessable at the root
http://192.168.1.77/
Only jackett is in a subdirectory
http://192.168.1.77/jackett

The rest about the ports and stuff is correct, i configured it like this to avoid exposing sonarr to the web incase somebody installs it on a vps, without knowing what hes doing.

**Comment by sasagr** [comment]
for some reason it did not work for me but I managed to connect to ports 8989 and 9117 removing the 127.0.0.1 everywhere in the yml and ngnix.conf files

**Comment by sasagr** [comment]
today I went for an update and I got this.
pi@raspberrypi:~/DockerPremiumize $ docker-compose pull
Pulling sonarr        ... done                                                                                          
Pulling jackett       ... done                                                                                          
Pulling premiumizephp ... error                                                                                        
Pulling reverseproxy  ... done                                                                                          
Pulling php           ... done                                                                                          
ERROR: for premiumizephp  pull access denied for premiumizephp_local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for premiumizephp_local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

is it normal to get this error considering that I built the premiumizephp myself?

**Comment by dgalli1** [comment]
Yes that's expected, incase that a new update comes out you also have to rebuild the image as described above
