### ISSUE TITLE
Radarr?

### ISSUE THREAD

**Issue by sasagr** [dgalli1/DockerPremiumize#2]
I managed to add Bazarr as companion, quite straight forward but do you have any plan to add Radarr?

**Comment by dgalli1** [comment]
Radarr shouldn't be that much work, can you make a pr with your bazarr config so that i can integrate it?

**Comment by sasagr** [comment]
Not sure I know how to do it.. As I know I should fork it and try to add it and submit but never did it before. In any case exactly what do you need? only the config.ini of bazarr? By the way I installed bazarr  with this docker-compose.yml I created:

version: "2.1"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /home/pi/bazarr:/config
      #- </path/to/movies>:/movies
      - /home/pi/DockerPremiumize/rclone/sonarr:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

**Comment by dgalli1** [comment]
alright nvm, will do it myself, shouldn't take to long anyways

**Comment by sasagr** [comment]
waiting to see Radarr alive too :)
If I can help you with my limited skill to have premiumizephp validated also for arm arch pls let me know so I dont have to build it manually every time there is an update.
Thanks anyway for your job!

**Comment by dgalli1** [comment]
Mh didn't want to waste that much time, anyways we now got automatic ARM Builds. And Bazzarr and Radarr.
You might just want to kill your existing Bazarr instalation and start with the one in the Docker-Compose File.

Please report back incase that the ARM Build is borked

**Comment by sasagr** [comment]
thanks a lot. very fast. I will try it as soon as I can and let you know

**Comment by sasagr** [comment]
update/installation worked without any big issues.. but I cannot launch radarr from browser. Sonarr and Bazarr are ok.
Did u forget to add something in nginx.conf?

**Comment by dgalli1** [comment]
Did you change
\- 127.0.0.1:7878:7878
in your docker-compose file? Default configuration is still limited to your own machine.
Otherwhise i would need the Logs from radarr
docker-compose logs radarr

**Comment by sasagr** [comment]
in my docker-compose I removed all the 127.0.0.1. From previous built I saw this is the only way I can connect to it from another machine and it works both locally and from other machine with Sonarr, Jacket, Bazarr but not with radarr. Also 7878 is not used by other servers.

version: "3.7"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - UMASK_SET=022 #optional
    volumes:
      - ./config_sonarr:/config
      - ./blackhole:/blackhole
      - ./rclone:/blackhole_watch
    ports:
      - 8989:8989
    expose: 
      - 8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - UMASK_SET=022 #optional
    volumes:
      - ./config_radarr:/config
      - ./rclone:/library
      - ./blackhole:/blackhole
    ports:
      - 7878:7878
    expose:
      - 7878
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - RUN_OPTS=<run options here> #optional
    volumes:
      - ./config_jackett:/config
      - ./blackhole:/downloads
    ports:
      - 9117:9117
    expose:
      - 9117
    restart: unless-stopped
  premiumizephp:
    image: dgalli1/premiumizephp:latest
    container_name: premiumizephp
    environment: 
      - API_KEY=zrejk9y4uu8xxxx
      - DOWNLOAD_FOLDER=PiOgQ4D10DQ0jGdxxxxxx
    volumes:
      - ./blackhole:/drophere
      - ./rclone:/watch_folder
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - UMASK_SET=022 #optional
    volumes:
      - ./config_bazarr:/config
      - ./rclone:/library
    ports:
      - 6767:6767
    restart: unless-stopped
  reverseproxy:
      image: nginx:latest
      ports:
          - 88:88
      volumes:
          - ./premiumizephp:/code
          - ./nginx.conf:/etc/nginx/nginx.conf

**Comment by sasagr** [comment]
the log..

pi@raspberrypi:~/DockerPremiumize $ docker-compose logs radarr
Attaching to radarr
radarr           | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
radarr           | [s6-init] ensuring user provided files have correct perms...exited 0.
radarr           | [fix-attrs.d] applying ownership & permissions fixes...
radarr           | [fix-attrs.d] done.
radarr           | [cont-init.d] executing container initialization scripts...
radarr           | [cont-init.d] 01-envfile: executing...
radarr           | [cont-init.d] 01-envfile: exited 0.
radarr           | [cont-init.d] 10-adduser: executing...
radarr           |
radarr           | -------------------------------------
radarr           |           _         ()
radarr           |          | |  ___   _    __
radarr           |          | | / __| | |  /  \
radarr           |          | | \__ \ | | | () |
radarr           |          |_| |___/ |_|  \__/
radarr           |
radarr           |
radarr           | Brought to you by linuxserver.io
radarr           | -------------------------------------
radarr           |
radarr           | To support the app dev(s) visit:
radarr           | Radarr: https://opencollective.com/radarr
radarr           |
radarr           | To support LSIO projects visit:
radarr           | https://www.linuxserver.io/donate/
radarr           | -------------------------------------
radarr           | GID/UID
radarr           | -------------------------------------
radarr           |
radarr           | User uid:    1000
radarr           | User gid:    1000
radarr           | -------------------------------------
radarr           |
radarr           | [cont-init.d] 10-adduser: exited 0.
radarr           | [cont-init.d] 30-config: executing...
radarr           | [cont-init.d] 30-config: exited 0.
radarr           | [cont-init.d] 99-custom-scripts: executing...
radarr           | [custom-init] no custom files found exiting...
radarr           | [cont-init.d] 99-custom-scripts: exited 0.
radarr           | [cont-init.d] done.
radarr           | [services.d] starting services
radarr           | [services.d] done.
pi@raspberrypi:~/DockerPremiumize $

**Comment by dgalli1** [comment]
Mh wierd it doesnt even output a error. And i just validated it on my computer and its working.
What happens if you rename the config_radarr folder to config_radarr_old and try again?

**Comment by sasagr** [comment]
it did not change.. before I asked you about nginx.conf because I noticed there no reference in it about radarr but I m not sure if this could make the difference

**Comment by sasagr** [comment]
Pls compare the two logs of sonarr and radarr.. It looks like radarr server did not start. As matter of fact if I look at the log in the config folder, it is not updating.

pi@raspberrypi:~/DockerPremiumize $ docker-compose logs radarr
Attaching to radarr
radarr           | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
radarr           | [s6-init] ensuring user provided files have correct perms...exited 0.
radarr           | [fix-attrs.d] applying ownership & permissions fixes...
radarr           | [fix-attrs.d] done.
radarr           | [cont-init.d] executing container initialization scripts...
radarr           | [cont-init.d] 01-envfile: executing...
radarr           | [cont-init.d] 01-envfile: exited 0.
radarr           | [cont-init.d] 10-adduser: executing...
radarr           |
radarr           | -------------------------------------
radarr           |           _         ()
radarr           |          | |  ___   _    __
radarr           |          | | / __| | |  /  \
radarr           |          | | \__ \ | | | () |
radarr           |          |_| |___/ |_|  \__/
radarr           |
radarr           |
radarr           | Brought to you by linuxserver.io
radarr           | -------------------------------------
radarr           |
radarr           | To support the app dev(s) visit:
radarr           | Radarr: https://opencollective.com/radarr
radarr           |
radarr           | To support LSIO projects visit:
radarr           | https://www.linuxserver.io/donate/
radarr           | -------------------------------------
radarr           | GID/UID
radarr           | -------------------------------------
radarr           |
radarr           | User uid:    1000
radarr           | User gid:    1000
radarr           | -------------------------------------
radarr           |
radarr           | [cont-init.d] 10-adduser: exited 0.
radarr           | [cont-init.d] 30-config: executing...
radarr           | [cont-init.d] 30-config: exited 0.
radarr           | [cont-init.d] 99-custom-scripts: executing...
radarr           | [custom-init] no custom files found exiting...
radarr           | [cont-init.d] 99-custom-scripts: exited 0.
radarr           | [cont-init.d] done.
radarr           | [services.d] starting services
radarr           | [services.d] done.
pi@raspberrypi:~/DockerPremiumize $ docker-compose logs sonarr
Attaching to sonarr
sonarr           | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
sonarr           | [s6-init] ensuring user provided files have correct perms...exited 0.
sonarr           | [fix-attrs.d] applying ownership & permissions fixes...
sonarr           | [fix-attrs.d] done.
sonarr           | [cont-init.d] executing container initialization scripts...
sonarr           | [cont-init.d] 01-envfile: executing...
sonarr           | [cont-init.d] 01-envfile: exited 0.
sonarr           | [cont-init.d] 10-adduser: executing...
sonarr           |
sonarr           | -------------------------------------
sonarr           |           _         ()
sonarr           |          | |  ___   _    __
sonarr           |          | | / __| | |  /  \
sonarr           |          | | \__ \ | | | () |
sonarr           |          |_| |___/ |_|  \__/
sonarr           |
sonarr           |
sonarr           | Brought to you by linuxserver.io
sonarr           | -------------------------------------
sonarr           |
sonarr           | To support the app dev(s) visit:
sonarr           | Sonarr: https://sonarr.tv/donate
sonarr           |
sonarr           | To support LSIO projects visit:
sonarr           | https://www.linuxserver.io/donate/
sonarr           | -------------------------------------
sonarr           | GID/UID
sonarr           | -------------------------------------
sonarr           |
sonarr           | User uid:    1000
sonarr           | User gid:    1000
sonarr           | -------------------------------------
sonarr           |
sonarr           | [cont-init.d] 10-adduser: exited 0.
sonarr           | [cont-init.d] 30-config: executing...
sonarr           | [cont-init.d] 30-config: exited 0.
sonarr           | [cont-init.d] 99-custom-scripts: executing...
sonarr           | [custom-init] no custom files found exiting...
sonarr           | [cont-init.d] 99-custom-scripts: exited 0.
sonarr           | [cont-init.d] done.
sonarr           | [services.d] starting services
sonarr           | [services.d] done.
sonarr           | [Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr.exe - Version 3.0.4.993
sonarr           | [Info] AppFolderInfo: Data directory is being overridden to [/config]
sonarr           | [Info] Router: Application mode: Interactive
sonarr           | [Info] MigrationLogger: *** Migrating data source=/config/sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
sonarr           | [Info] MigrationLogger: *** Migrating data source=/config/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
sonarr           | [Info] OwinHostController: Listening on the following URLs:
sonarr           | [Info] OwinHostController:   http://*:8989/
sonarr           | [Info] SonarrBootstrapper: Starting Web Server
pi@raspberrypi:~/DockerPremiumize $

**Comment by dgalli1** [comment]
Yes i know that its is not running, but i can't really help you because its not a issue of my repo. I guess you should head over to the radarr repo if it still doesn't run with a renamed config.

**Comment by sasagr** [comment]
wait a sec... I think the config test did not work. I renamed the config_radarr folder to config_radarr_old and did a git pull but it did not add an new folder. Then I did a down + up and it created an empty config_radarr folder. Did I do something wrong?

**Comment by dgalli1** [comment]
Git pull should not add anything that you deleted your self, thats kinda the point of git.
Nope it seems like you did everything correct, in this case its most likely a bug in radarr.

**Comment by sasagr** [comment]
I see.. I will try to install radarr outside your repo and see. By the way why did u choose the nightly?

**Comment by sasagr** [comment]
ok solved it. I changed the docker-compose file with a different image
radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr

taken from the docker hub
https://hub.docker.com/r/linuxserver/radarr

If you dont see a problem maybe you can update the docker-compose with this image

**Comment by sasagr** [comment]
:( I just saw another issue.. settings tab is not responding (loading for ever)
maybe it does not like your config folder. I will rename and try but eventually I will need the part to pick the premiumize downloader

**Comment by sasagr** [comment]
yes as expected.. renaming your config folder it worked , it created a new one but I lost the premiumize downloader.
I will leave it to at this point... :)

**Comment by sasagr** [comment]
I found the problem in the nightly release you add in the yml. The raspberry pi need to update the libseccomp2 to be able to work
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.0-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.0-1_armhf.deb

So at this point updating this package your yml is ok. By the way I preferred to still use the same volumes mapping also for radarr and I dont see major issues:

volumes:
      - ./config_radarr:/config
      - ./rclone:/blackhole_watch
      - ./blackhole:/blackhole
